# BSD 3-Clause License
# Copyright (c) 2022, Laineil
# All rights reserved.

---

- name: restart mariadb
  service:
    name: '{{ mariadb_service }}'
    state: restarted
  tags: mariadb_service_restart