# BSD 3-Clause License
# Copyright (c) 2022, Laineil
# All rights reserved.

---
- name: Add the OS specific varibles
  include_vars: "group_vars/{{ ansible_distribution }}{{ ansible_distribution_major_version }}.yml"
- import_tasks: mariadb_00_pause.yml
- import_tasks: mariadb_01_repo.yml
- import_tasks: mariadb_02_install.yml
- import_tasks: mariadb_03_service.yml
- import_tasks: mariadb_04_initial.yml
- import_tasks: mariadb_05_admin.yml
